using System.Net;
using System.Text;
using System.Text.Json;

namespace DepSphere.Analyzer;

public static class SourceCodeViewerHtmlBuilder
{
    public static string Build(SourceCodeDocument document, IReadOnlyDictionary<string, string>? symbolLinks = null)
    {
        var path = WebUtility.HtmlEncode(document.FilePath);
        var contentBase64 = Convert.ToBase64String(Encoding.UTF8.GetBytes(document.Content ?? string.Empty));
        var linksJson = JsonSerializer.Serialize(symbolLinks ?? new Dictionary<string, string>());
        var linksBase64 = Convert.ToBase64String(Encoding.UTF8.GetBytes(linksJson));

        var builder = new StringBuilder();
        builder.AppendLine("<!DOCTYPE html>");
        builder.AppendLine("<html lang=\"ja\">");
        builder.AppendLine("<head>");
        builder.AppendLine("  <meta charset=\"utf-8\" />");
        builder.AppendLine("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\" />");
        builder.AppendLine("  <title>DepSphere Source Viewer</title>");
        builder.AppendLine("  <style>");
        builder.AppendLine("    html, body { margin: 0; padding: 0; background: #0f172a; color: #e2e8f0; }");
        builder.AppendLine("    #header { padding: 8px 12px; font: 12px ui-monospace, SFMono-Regular, Menlo, monospace; background: #111827; border-bottom: 1px solid #334155; }");
        builder.AppendLine("    #dep-source-viewer { width: 100vw; height: calc(100vh - 56px); box-sizing: border-box; background: #1e1e1e; }");
        builder.AppendLine("    #dep-source-viewer-fallback { width: 100vw; height: calc(100vh - 56px); box-sizing: border-box; border: 0; resize: none; background: #020617; color: #e2e8f0; font: 13px/1.45 ui-monospace, SFMono-Regular, Menlo, monospace; padding: 12px; display: none; }");
        builder.AppendLine("    .dep-line-highlight { border-left: 2px solid #22d3ee; background: rgba(34, 211, 238, 0.08); }");
        builder.AppendLine("    #hint { padding: 4px 12px; color: #94a3b8; font: 11px ui-monospace, SFMono-Regular, Menlo, monospace; border-top: 1px solid #1e293b; }");
        builder.AppendLine("  </style>");
        builder.AppendLine("</head>");
        builder.AppendLine("<body>");
        builder.AppendLine($"  <div id=\"header\">{path} (L{document.StartLine}-L{document.EndLine})</div>");
        builder.AppendLine("  <div id=\"dep-source-viewer\"></div>");
        builder.AppendLine("  <textarea id=\"dep-source-viewer-fallback\" readonly></textarea>");
        builder.AppendLine("  <div id=\"hint\">シンボルをダブルクリックで関連ノードへジャンプ</div>");
        builder.AppendLine("  <script src=\"https://unpkg.com/monaco-editor@0.45.0/min/vs/loader.js\"></script>");
        builder.AppendLine("  <script>");
        builder.AppendLine($"    const depSourceBase64 = \"{contentBase64}\";");
        builder.AppendLine($"    const depSymbolLinks = JSON.parse(atob(\"{linksBase64}\"));");
        builder.AppendLine($"    const depStartLine = {document.StartLine};");
        builder.AppendLine($"    const depEndLine = {document.EndLine};");
        builder.AppendLine("    const viewer = document.getElementById('dep-source-viewer');");
        builder.AppendLine("    const fallback = document.getElementById('dep-source-viewer-fallback');");
        builder.AppendLine("    function postNodeSelected(nodeId) {");
        builder.AppendLine("      const payload = { type: 'nodeSelected', nodeId: nodeId };");
        builder.AppendLine("      if (window.chrome && window.chrome.webview && window.chrome.webview.postMessage) {");
        builder.AppendLine("        window.chrome.webview.postMessage(payload);");
        builder.AppendLine("      }");
        builder.AppendLine("      if (window.__depSphereHost && typeof window.__depSphereHost.onNodeSelected === 'function') {");
        builder.AppendLine("        window.__depSphereHost.onNodeSelected(nodeId);");
        builder.AppendLine("      }");
        builder.AppendLine("    }");
        builder.AppendLine("    function decodeBase64Utf8(base64) {");
        builder.AppendLine("      const raw = atob(base64);");
        builder.AppendLine("      const bytes = new Uint8Array(raw.length);");
        builder.AppendLine("      for (let i = 0; i < raw.length; i++) { bytes[i] = raw.charCodeAt(i); }");
        builder.AppendLine("      return new TextDecoder('utf-8').decode(bytes);");
        builder.AppendLine("    }");
        builder.AppendLine("    function tryJumpByToken(token) {");
        builder.AppendLine("      if (!token) return;");
        builder.AppendLine("      const nodeId = depSymbolLinks[token];");
        builder.AppendLine("      if (!nodeId) return;");
        builder.AppendLine("      postNodeSelected(nodeId);");
        builder.AppendLine("    }");
        builder.AppendLine("    function initializeFallbackView(sourceText) {");
        builder.AppendLine("      viewer.style.display = 'none';");
        builder.AppendLine("      fallback.style.display = 'block';");
        builder.AppendLine("      fallback.value = sourceText;");
        builder.AppendLine("      if (fallback.dataset.bound === 'true') return;");
        builder.AppendLine("      fallback.dataset.bound = 'true';");
        builder.AppendLine("      fallback.addEventListener('dblclick', () => {");
        builder.AppendLine("        const start = fallback.selectionStart || 0;");
        builder.AppendLine("        const end = fallback.selectionEnd || 0;");
        builder.AppendLine("        if (end <= start) return;");
        builder.AppendLine("        const token = fallback.value.substring(start, end).trim();");
        builder.AppendLine("        tryJumpByToken(token);");
        builder.AppendLine("      });");
        builder.AppendLine("    }");
        builder.AppendLine("    function monacoWorkerBootstrap() {");
        builder.AppendLine("      return \"self.MonacoEnvironment={baseUrl:'https://unpkg.com/monaco-editor@0.45.0/min/'};importScripts('https://unpkg.com/monaco-editor@0.45.0/min/vs/base/worker/workerMain.js');\";");
        builder.AppendLine("    }");
        builder.AppendLine("    function initializeMonaco(sourceText) {");
        builder.AppendLine("      if (!window.require) return false;");
        builder.AppendLine("      window.MonacoEnvironment = {");
        builder.AppendLine("        getWorkerUrl: function() {");
        builder.AppendLine("          return 'data:text/javascript;charset=utf-8,' + encodeURIComponent(monacoWorkerBootstrap());");
        builder.AppendLine("        }");
        builder.AppendLine("      };");
        builder.AppendLine("      window.require.config({ paths: { vs: 'https://unpkg.com/monaco-editor@0.45.0/min/vs' } });");
        builder.AppendLine("      window.require(['vs/editor/editor.main'], function() {");
        builder.AppendLine("        const editor = window.monaco.editor.create(viewer, {");
        builder.AppendLine("          value: sourceText,");
        builder.AppendLine("          language: 'csharp',");
        builder.AppendLine("          theme: 'vs-dark',");
        builder.AppendLine("          readOnly: true,");
        builder.AppendLine("          minimap: { enabled: false },");
        builder.AppendLine("          lineNumbers: 'on',");
        builder.AppendLine("          automaticLayout: true,");
        builder.AppendLine("          scrollBeyondLastLine: false,");
        builder.AppendLine("          tabSize: 4,");
        builder.AppendLine("          renderLineHighlight: 'line'");
        builder.AppendLine("        });");
        builder.AppendLine("        editor.revealLineInCenter(depStartLine);");
        builder.AppendLine("        const endLine = Math.max(depStartLine, depEndLine);");
        builder.AppendLine("        editor.deltaDecorations([], [{");
        builder.AppendLine("          range: new window.monaco.Range(depStartLine, 1, endLine, 1),");
        builder.AppendLine("          options: { isWholeLine: true, className: 'dep-line-highlight' }");
        builder.AppendLine("        }]);");
        builder.AppendLine("        editor.onMouseDown(function(event) {");
        builder.AppendLine("          if (!event.event || event.event.detail !== 2) return;");
        builder.AppendLine("          setTimeout(function() {");
        builder.AppendLine("            const selection = editor.getSelection();");
        builder.AppendLine("            if (!selection) return;");
        builder.AppendLine("            const token = editor.getModel().getValueInRange(selection).trim();");
        builder.AppendLine("            tryJumpByToken(token);");
        builder.AppendLine("          }, 0);");
        builder.AppendLine("        });");
        builder.AppendLine("      }, function() {");
        builder.AppendLine("        initializeFallbackView(sourceText);");
        builder.AppendLine("      });");
        builder.AppendLine("      return true;");
        builder.AppendLine("    }");
        builder.AppendLine("    const sourceText = decodeBase64Utf8(depSourceBase64);");
        builder.AppendLine("    if (!initializeMonaco(sourceText)) {");
        builder.AppendLine("      initializeFallbackView(sourceText);");
        builder.AppendLine("    }");
        builder.AppendLine("    setTimeout(function() {");
        builder.AppendLine("      if (!window.monaco) {");
        builder.AppendLine("        if (fallback.style.display !== 'block') {");
        builder.AppendLine("          initializeFallbackView(sourceText);");
        builder.AppendLine("        }");
        builder.AppendLine("      }");
        builder.AppendLine("    }, 1200);");
        builder.AppendLine("  </script>");
        builder.AppendLine("</body>");
        builder.AppendLine("</html>");
        return builder.ToString();
    }
}
